ING-453 Return not stored error from not stored status
couchbase/gocbcorex pull request #181
Opened 2023-11-06 11:36 UTC by Westwooo

MutateIn with Insert semantics can return NotStored. This should be changed so that we handle NotStored in gocbcorex for a MutateIn with Insert semantics by converting it into a DocAlreadyExists error.

2023-11-06 21:30 UTC, brett19 requested changes
Based on more recent comments on ING-453 and ING-623, we should probably have StatusNotStored converted into ErrDocExists when the MutateIn operation is executing with Insert semantics.  In other cases, it should return ErrNotStored as it does now in this PR.

2023-11-07 10:41 UTC, Westwooo commented
> Based on more recent comments on ING-453 and ING-623, we should probably have StatusNotStored converted into ErrDocExists when the MutateIn operation is executing with Insert semantics. In other cases, it should return ErrNotStored as it does now in this PR.

@brett19 done. I haven't added a test for this due to the difficulty I had reproducing the NotStored status. Is there any way that we can mock rpcs that would allow us to manually cause a NotStoresStatus to be returned? Or is there some other method for testing suck edge cases?

2023-11-07 18:11 UTC, brett19 commented
Unfortunately, this particular error shows up as a race condition if two MutateIn(w/ Insert Semantics) race together, one of them could fail with NotStored rather than DocExists.  We could theoretically add a test that validates that OpsCore correctly processes a NotStored into a DocExists, but realistically this would not be testing very much. I think you can use this test as an example if you were so inclined: https://github.com/couchbase/gocbcorex/blob/master/memdx/ops_crud_test.go#L2263

2023-11-07 19:01 UTC, Westwooo commented
> Unfortunately, this particular error shows up as a race condition if two MutateIn(w/ Insert Semantics) race together, one of them could fail with NotStored rather than DocExists. We could theoretically add a test that validates that OpsCore correctly processes a NotStored into a DocExists, but realistically this would not be testing very much. I think you can use this test as an example if you were so inclined: https://github.com/couchbase/gocbcorex/blob/master/memdx/ops_crud_test.go#L2263

I'll just leave the test then

2023-11-07 19:03 UTC, brett19 commented
Sounds good.  The code looks good, just needs to be rebased on more recent changes (it won't allow me to do it in GitHub directly).

2023-11-07 19:10 UTC, brett19 approved these changes

2023-11-07 19:10 UTC, merged