ING-841: Leverage redaction helpers where appropriate
couchbase/gocbcorex pull request #288
Opened 2024-09-18 13:53 UTC by Westwooo

2024-09-18 13:55 UTC, Westwooo commented on .github/workflows/lint.yml
> +          go install golang.org/x/tools/cmd/goimports@v0.24.0
When using `@latest` was getting: 

```
Run go install golang.org/x/tools/cmd/goimports@latest
  go install golang.org/x/tools/cmd/goimports@latest
  shell: /usr/bin/bash -e {0}
go: downloading golang.org/x/tools v0.[2](https://github.com/couchbase/gocbcorex/actions/runs/10923246546/job/30319407860?pr=288#step:4:2)5.0
go: golang.org/x/tools/cmd/goimports@latest (in golang.org/x/tools@v0.25.0): go.mod:[3](https://github.com/couchbase/gocbcorex/actions/runs/10923246546/job/30319407860?pr=288#step:4:3): invalid go version '1.22.0': must match format 1.23
```

2024-09-23 06:40 UTC, brett19 requested changes

2024-09-23 06:40 UTC, brett19 commented on transactionsx/losttransactioncleaner.go
> +		zaputils.FQDocID("uuid", c.atrAgent.BucketName(), c.atrScopeName, c.atrCollectionName, []byte(c.uuid)))
I think this should be a uuid field with the UUID, and a FQCollectionName() rather than describing the UUID as being a document name.

2024-09-23 07:03 UTC, brett19 approved these changes

2024-09-23 07:07 UTC, merged