ING-782: Add handling for query index build fails
couchbase/gocbcorex pull request #302
Opened 2024-12-17 10:24 UTC by chvck

2024-12-19 19:22 UTC, brett19 requested changes

2024-12-19 19:22 UTC, brett19 commented on cbqueryx/queryrespreader.go
> +		if strings.Contains(lowerMsg, "build index fails") {
This message should probably include the 'will retry' text, since that's an important detail to how this error is used.

2025-01-06 11:21 UTC, Westwooo approved these changes

2025-01-08 09:04 UTC, brett19 approved these changes

2025-01-08 09:10 UTC, merged